organ_labels = [
    # "spleen",
    # "kidney_right",
    # "kidney_left",
    # "gallbladder",
    "liver",
    # "stomach",
    # "pancreas",
    # "lung_upper_lobe_left",
    # "lung_lower_lobe_left",
    # "lung_upper_lobe_right",
    # "lung_middle_lobe_right",
    # "lung_lower_lobe_right",
    # "trachea",
    # "thyroid_gland",
    # "duodenum",
    # "intestine",
    # "urinary_bladder",
    # "prostate",
    # "aorta",
    # "brachiocephalic_trunk",
    # "common_carotid_artery_right",
    # "common_carotid_artery_left",
    # "humerus_left",
    # "humerus_right",
    # "scapula_left",
    # "scapula_right",
    # "clavicula_left",
    # "clavicula_right",
    # "femur_left",
    # "femur_right",
    # "hip_left",
    # "hip_right",
    # "sternum",
    # "sacrum",
    # "vertebrae_L5",
    # "vertebrae_L4",
    # "vertebrae_L3",
    # "vertebrae_L2",
    # "vertebrae_L1",
    # "vertebrae_T12",
    # "vertebrae_T11",
    # "vertebrae_T10",
    # "vertebrae_T9",
    # "vertebrae_T8",
    # "vertebrae_T7",
    # "vertebrae_T6",
    # "vertebrae_T5",
    # "vertebrae_T4",
    # "vertebrae_T3",
    # "vertebrae_T2",
    # "vertebrae_T1",
    # "vertebrae_C7",
    # "vertebrae_C6",
    # "vertebrae_C5",
    # "vertebrae_C4",
    # "vertebrae_C3",
    # "vertebrae_C2",
    # "vertebrae_C1",
    # "colon",
    # "rib_left_1",
    # "rib_left_2",
    # "rib_left_3",
    # "rib_left_4",
    # "rib_left_5",
    # "rib_left_6",
    # "rib_left_7",
    # "rib_left_8",
    # "rib_left_9",
    # "rib_left_10",
    # "rib_left_11",
    # "rib_left_12",
    # "rib_right_1",
    # "rib_right_2",
    # "rib_right_4",
    # "rib_right_3",
    # "rib_right_5",
    # "rib_right_6",
    # "rib_right_7",
    # "rib_right_8",
    # "rib_right_9",
    # "rib_right_10",
    # "rib_right_11",
    # "rib_right_12",
    # "costal_cartilages",
    # "gonads",
    # "heart_atrium_left",
    # "heart_atrium_right",
    # "heart_tissue",
    # "heart_myocardium",
    # "heart_ventricle_left",
    # "heart_ventricle_right",
    # "sternum_manubrium",
    # "sternum_corpus"
]

selected_organ_labels = [
    "spleen",
    "kidney_right",
    "kidney_left",
    "liver",
    "stomach",
    "pancreas",
    "lung_right",
    "lung_left",
    "trachea",
    "thyroid_gland",
    "duodenum",
    "urinary_bladder",
    "aorta",
    "scapula_left",
    "scapula_right",
    "clavicula_left",
    "clavicula_right",
    "femur_left",
    "femur_right",
    "hip_left",
    "hip_right",
    "sacrum",
    "vertebrae_L5",
    "vertebrae_L4",
    "vertebrae_L3",
    "vertebrae_L2",
    "vertebrae_L1",
    "vertebrae_T12",
    "vertebrae_T11",
    "vertebrae_T10",
    "vertebrae_T9",
    "vertebrae_T8",
    "vertebrae_T7",
    "vertebrae_T6",
    "vertebrae_T5",
    "vertebrae_T4",
    "vertebrae_T3",
    "vertebrae_T2",
    "vertebrae_T1",
    "vertebrae_C7",
    "vertebrae_C6",
    "heart"
]