# Data Settings
train_data_file_path: /home/eytan/storage/staff/eytankats/data/nako_10k/masks_volumetric_preprocessed_v2/training_masks_list.csv
val_data_file_path: /home/eytan/storage/staff/eytankats/data/nako_10k/masks_volumetric_preprocessed_v2/validation_masks_list.csv
test_data_file_path: /home/eytan/storage/staff/eytankats/data/nako_10k/masks_volumetric_preprocessed_v2/test_masks_list.csv
images_dir: /home/eytan/storage/staff/eytankats/data/nako_10k/images_depth/
volumes_dir: /home/eytan/storage/staff/eytankats/data/nako_10k/images_mri_stitched/
masks_pattern: /home/eytan/storage/staff/eytankats/data/nako_10k/masks_volumetric_preprocessed_v2/*.nii.gz
labels_file: /home/eytan/storage/staff/eytankats/data/nako_10k/labels_processed_aggregated_v2.json
output_path: /home/eytan/projects/orgloc/experiments/ # /home/eytan/storage/staff/eytankats/projects/orgloc/experiments/
experiment_id: multidim_multilabel_alllabels_lr1e-4warm4000_unet_processed_aggmasksv2

# Model choice
model: basic_unet
#model: attention_unet
#model: swin_unet
#model: segformer

# Training settings
num_examples: 10000
iterations: 15001
GPUs: [0]
num_workers: 8
batch_size: 8
seed: 1987
lr: 0.0001
w_ce: 1
w_dice: 1

# Test settings
dropout: 0.0
save_imgs: 10
test_experiment_id: 202506251345_multidim_multilabel_unet_processed_aggmasksv2
test_checkpoint: best_valid_loss.pth



