# Data Settings
train_data_file_path: /home/kats/storage/staff/eytankats/data/nako_10k/masks_projection/training_masks_filtered_info.csv
val_data_file_path: /home/kats/storage/staff/eytankats/data/nako_10k/masks_projection/validation_masks_filtered_info.csv
test_data_file_path: /home/kats/storage/staff/eytankats/data/nako_10k/masks_projection/test_masks_filtered_info.csv
images_dir: /home/kats/storage/staff/eytankats/data/nako_10k/images_depth/
masks_dir: /home/kats/storage/staff/eytankats/data/nako_10k/masks_projection/
output_path: /home/kats/storage/staff/eytankats/projects/orgloc/experiments/

# Training Settings
model: basic_unet
#model: attention_unet
#model: swin_unet
#model: segformer

num_examples: 10000
iterations: 15001
GPUs: [0]
num_workers: 8
batch_size: 16
seed: 1987

# Optimizer Settings
lr: 0.001

# Loss Settings
w_ce: 1
w_dice: 1


