# Data Settings
phase: train
anatomy: liver
pickle_file_path: /home/kats/storage/staff/eytankats/projects/genseg/data/nako_10k/nako10k.pkl
snapshot_path: /home/kats/storage/staff/eytankats/projects/genseg/experiments/

# Training Settings
#model: basic_unet
model: attention_unet
#model: swin_unet
#model: segformer
num_examples: 10000
iterations: 15001
epochs: 1000
GPUs: [0]
num_workers: 8
batch_size: 16
save_freq: 10
seed: 2333

# Model Settings
#in_channel: 4
#out_channels: 4
#num_res_blocks: 2
#ch: 32
#ch_mult: [1,2,4,4]

in_channel: 4
out_channels: 4
num_res_blocks: 1
ch: 32
ch_mult: [1,1,2,2]

# Optimizer Settings
lr: 0.001

# Loss Settings
w_rec: 1
w_dice: 1


